/* A packrat parser generated by PackCC 1.6.0 */

#ifndef PCC_INCLUDED___PEG_ELMISH_H
#define PCC_INCLUDED___PEG_ELMISH_H

struct parserCtx;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct pelmish_context_tag pelmish_context_t;

pelmish_context_t *pelmish_create(struct parserCtx *auxil);
int pelmish_parse(pelmish_context_t *ctx, int *ret);
void pelmish_destroy(pelmish_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED___PEG_ELMISH_H */
