sed -i 's/input.kt/input.elmish/g' elmish-comments.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-destructuring.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-extensions.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-generics.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-invalid-input.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-rawstrings.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-scope.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-strings.d/expected.tags
sed -i 's/input.kt/input.elmish/g' elmish-syntax.d/expected.tags
